services:
  app:
    build: .
    container_name: landing-app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "7010"
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: temp-amdaani-admin-fronted_app-network
