export const themeConfig = {
  light: {
    background: "bg-[#F5F7FA]",
    card: "bg-white",
    text: "text-[#1C1C1E]",
    textSecondary: "text-[#5F6368]",
    textTertiary: "text-[#80868B]",
    buttonPrimary: "bg-[#1A73E8] text-white hover:bg-[#1967D2]",
    buttonSecondary:
      "border border-[#1A73E8] text-[#1A73E8] hover:bg-[#E8F0FE]",
    buttonTertiary: "border border-[#C5C8CD] text-[#1C1C1E] hover:bg-[#F8F9FA]",
    accent: "bg-[#1A73E8]",
    accentLight: "bg-[#E8F0FE]",
    surface: "bg-white",
    surfaceVariant: "bg-[#F8F9FA]",
    outline: "border-[#C5C8CD]",
    success: "text-[#34A853]",
    warning: "text-[#FBBC05]",
    error: "text-[#D93025]",
  },
  dark: {
    background: "bg-[#0E0F11]",
    card: "bg-[#1C1C1E]",
    text: "text-[#E8EAED]",
    textSecondary: "text-[#9AA0A6]",
    textTertiary: "text-[#80868B]",
    buttonPrimary: "bg-[#8AB4F8] text-[#0D47A1] hover:bg-[#7AA3F7]",
    buttonSecondary:
      "border border-[#8AB4F8] text-[#8AB4F8] hover:bg-[#1F1F1F]",
    buttonTertiary: "border border-[#3A3B3C] text-[#E8EAED] hover:bg-[#2C2C2E]",
    accent: "bg-[#8AB4F8]",
    accentLight: "bg-[#1F1F1F]",
    surface: "bg-[#1C1C1E]",
    surfaceVariant: "bg-[#2C2C2E]",
    outline: "border-[#3A3B3C]",
    success: "text-[#81C995]",
    warning: "text-[#FDE293]",
    error: "text-[#F28B82]",
  },
};
